config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#index', via: :get
  resource :dashboard, only: [:show]
  resources :audio_files, only: [:new, :create, :edit, :update]
  resources :snippets, only: [:new, :create, :edit, :update, :destroy]
  resources :suggestions_job_statuses, only: [:show]
  resources :users, only: [:create]
  resources :wishlists, only: [:new, :create, :edit, :update]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :subject, polymorphic: true

  enum status: {
    created: 0,
    updated: 1,
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_file.rb
class AudioFile < ApplicationRecord
  belongs_to :user
  has_one :activity, dependent: :destroy, as: :subject
  validates :artist, :title, :audio, presence: true
  has_attached_file :audio, attachment_presence: true
  validates_attachment_content_type :audio, content_type: /\Aaudio\/.*\z/
end

app/models/audio_files.rb
class AudioFiles < ApplicationRecord
  belongs_to :user
  validates :artist, :title, :audio, presence: true
  has_attached_file :audio
  validates_attachment_content_type :audio, content_type: ".mp3"
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user
  has_one :activity, dependent: :destroy, as: :subject
  validates :artist, :title, :notes, presence: true
end

app/models/suggestions_job_status.rb
class SuggestionsJobStatus < ApplicationRecord
  validates :done, inclusion: { in: [true, false] }
  validates :done, exclusion: { in: [nil] }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_one :dashboard
  has_many :activities
  has_many :audio_files
  has_many :snippets
  has_many :wishlists

  validates :email, :username, uniqueness: true
  validates :password, presence: true, on: :create
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_one :activity, dependent: :destroy, as: :subject
  validates :artist, :title, :instrument, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  before_action :require_login

  private

  def record_activity(subject:, status:)
    Activity.create!(
      subject: subject,
      user: current_user,
      status: status,
    )
  end
end

app/controllers/audio_files_controller.rb
class AudioFilesController < ApplicationController
  def new
    @audio_file = AudioFile.new
  end

  def create
    @audio_file = current_user.audio_files.new(audio_file_params)
    if @audio_file.save
      record_activity(subject: @audio_file, status: "created")
      redirect_to dashboard_url, notice: "Audio file created! You rock."
    else
      render :new, status: 400
    end
  end

  def edit
    @audio_file = current_user.audio_files.find(params[:id])
  end

  def update
    @audio_file = current_user.audio_files.find(params[:id])
    if @audio_file.update(audio_file_params)
      record_activity(subject: @audio_file, status: "updated")
      redirect_to dashboard_url, notice: "Audio file updated successfully."
    else
      render :edit, status: 400
    end
  end

  private

  def audio_file_params
    params.require(:audio_file).permit(:artist, :title, :audio)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = current_user
  end

  def show
    @job_status = SuggestionsJobStatus.create!
    job = GetSuggestionsJob.perform_later(@job_status)
    @job_status.update!(jobid: job.provider_job_id)

    @activities = current_user.activities.order("created_at DESC")
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = current_user.snippets.new(snippet_params)
    if @snippet.save
      record_activity(subject: @snippet, status: "created")
      redirect_to dashboard_url, notice: "Snippet created! You rock."
    else
      render :new, status: 400
    end
  end

  def edit
    @snippet = current_user.snippets.find(params[:id])
  end

  def update
    @snippet = current_user.snippets.find(params[:id])
    if @snippet.update(snippet_params)
      record_activity(subject: @snippet, status: "updated")
      redirect_to dashboard_url, notice: "Snippet updated successfully."
    else
      render :edit, status: 400
    end
  end

  def destroy
    @snippet = current_user.snippets.find(params[:id])
    @snippet.destroy!
    redirect_to dashboard_url, notice: "Your snippet has been deleted."
  end

  private

  def snippet_params
    params.require(:snippet).permit(:artist, :title, :notes)
  end
end

app/controllers/suggestions_job_statuses_controller.rb
class SuggestionsJobStatusesController < ApplicationController
  def show
    job_status = SuggestionsJobStatus.find(params[:id])
    if !job_status.done?
      render json: {}, status: 202
    elsif job_status.done?
      render json: job_status, status: 201
    else
      render json: {}, status: 422
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def create
    @user = user_from_params
    if @user.save
      sign_in @user
      redirect_to dashboard_path, notice: "Sign up successful! You rock."
    else
      redirect_to sign_up_path, notice: "Sign up unsuccessful. Please try again."
    end
  end

  private

  def user_from_params
    email = user_params.delete(:email)
    username = user_params.delete(:username)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new.tap do |user|
      user.email = email
      user.username = username
      user.password = password
    end
  end

  def user_params
    params.fetch(Clearance.configuration.user_parameter, Hash.new)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def new
    @wishlist = Wishlist.new
  end

  def create
    @wishlist = current_user.wishlists.new(wishlist_params)
    if @wishlist.save
      record_activity(subject: @wishlist, status: "created")
      redirect_to dashboard_url, notice: "Wishlist item created! You rock."
    else
      render :new, status: 400
    end
  end

  def edit
    @wishlist = current_user.wishlists.find(params[:id])
  end

  def update
    @wishlist = current_user.wishlists.find(params[:id])
    if @wishlist.update(wishlist_params)
      record_activity(subject: @wishlist, status: "updated")
      redirect_to dashboard_url, notice: "Wishlist item updated successfully."
    else
      render :edit, status: 400
    end
  end

  private

  def wishlist_params
    params.require(:wishlist).permit(:artist, :title, :instrument)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activity.html.erb
<h3 class="snippet-info">
<%= activity.subject.title %>, by <%= activity.subject.artist %></h3>

<p class="saved-by">
<%= activity.subject_type.underscore.humanize %> <%= activity.status %> by: <%= activity.user.username %></p>

<%= render activity.subject %>
<h3 class="snippet-info"><%= activity.created_at.to_formatted_s %></h3>

<br/><br/><br/>

app/views/audio_files/_audio_file.html.slim
h3 class="snippet-info"
  = "Audio File: #{audio_file.audio}"

app/views/audio_files/edit.html.slim
h1
  = "Update your audio file:"

= simple_form_for @audio_file, method: "patch" do |f|
  = f.input :artist
  = f.input :title
  = f.input :audio
  = f.button :submit

= simple_form_for @audio_file, method: :delete do |f|
  = f.button :submit, "Delete"

app/views/audio_files/new.html.slim
= simple_form_for @audio_file do |f|
  = f.input :artist
  = f.input :title
  = f.input :audio
  = f.button :submit

app/views/dashboards/index.html.erb
<div id="intro">
  <h1>Welcome to Music Snippets!</h1>
  <h3>Music Snippets is an app for musicians to quickly and easily save guitar tab or music note snippets from songs for easy reference later.</h3>
  <h3> <%= link_to "Sign Up", sign_up_path %>, <%= link_to "Sign In", sign_in_path %>, or just dive in and <%= link_to "explore", dashboard_path %>!</h3>

<div id="footer">
  <p>
    🎹 🎸 Built by <a href="https://github.com/entcheva">@entcheva</a> with
    <a href="http://rubyonrails.org/">Ruby On Rails</a>,
    <a href="http://sass-lang.com/">Sass</a>,
    <a href="http://bourbon.io/">Bourbon</a>,
    <a href="http://neat.bourbon.io/">Neat</a>.🎷🦄
  </p>
</div>

app/views/dashboards/show.html.erb
<div id='dashboard-header'>
  <h1 class="dashboard-title">Welcome to the Music Snippets dashboard!</h1>
  <%= link_to "Save a snippet", new_snippet_path %>
  <%= link_to "Save an audio file", new_audio_file_path %>
  <%= link_to "Save a wishlist item", new_wishlist_path %>
</div>

<hr>
<h1 class="dashboard-title">🎹🎸 Latest activity:</h1>
<div class="snippet">
  <%= render @activities %>
</div>

<hr>
<h1 class="dashboard-title">🎹🎸 Music suggestions:</h1>

<script type="text/javascript">

function getJobStatus(jobId) {
  $.ajax({
    url: "/suggestions_job_statuses/" + jobId,
    type: "GET",
    dataType: "json",
    error: function(xhr, errorString, exceptionObj) {
      console.log(errorString);
      console.log(xhr);
      console.log(exceptionObj);
      console.log("so sad");
    },
    statusCode: {
      202: function (data, status, xhr) {
        setTimeout(getJobStatus, 1000, jobId);
      },
      201: function (data, status, xhr) {
        $("#image").append("<img src='" + data.payload.image + "'/>");
        $("#artist").append(data.payload.artist);
        $("#track_title").append(data.payload.title);
        $("#album").append(data.payload.album);
        $("#message").append(data.message);
      },
    },
    success: function(data, statusString, xhr){
      console.log(data);
      console.log(data.payload);
      console.log(statusString);
      console.log(xhr);
      console.log(xhr.status);
    },
  });
}

var jobId = "<%= @job_status.id%>";
getJobStatus(jobId);
</script>

<div class="snippet">
  <div id="suggestion">

    <div id="message"></div>

    <div id="image"></div>

    <p class="saved-by">Artist</p>
    <h3 class="snippet-info"><div id="artist"></div></h3>

    <p class="saved-by">Track</p>
    <h3 class="snippet-info"><div id="track_title"></div></h3>

    <p class="saved-by">Album</p>
    <h3 class="snippet-info"><div id="album"></div></h3>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <title>music_snippets</title>
</head>
<body>
  <div id="nav">
    <div id="current-user-options">
      <% if signed_in? -%>
        Hi, <%= current_user.username %> | <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
      <% else -%>
        <%= link_to t(".sign_in"), sign_in_path %>
      <% end -%>
    </div>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/snippets/_snippet.html.slim
h3 class="snippet-info"
  = "Notes: #{snippet.notes}"

app/views/snippets/edit.html.erb
<h1>Update your music snippet:</h1>

<%= simple_form_for @snippet, method: "patch" do |f| %>
  <%= f.input :artist %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.button :submit %>
<% end %>

<%= simple_form_for @snippet, method: :delete do |f| %>
  <%= f.button :submit, "Delete" %>
<% end %>

app/views/snippets/new.html.erb
<h1>Save a new music snippet:</h1>

<%= simple_form_for @snippet do |f| %>
  <%= f.input :artist %><br/>
  <%= f.input :title %><br/>
  <%= f.input :notes %><br/>
  <%= f.button :submit %>
<% end %>

app/views/users/_form.html.erb
<div class="user-form">
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="text-field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
</div>

app/views/wishlists/_wishlist.html.slim
h3 class="snippet-info"
  = "Instrument: #{wishlist.instrument}"

app/views/wishlists/edit.html.slim
h1
  = "Update your wishlist item:"

= simple_form_for @wishlist, method: "patch" do |f|
  = f.input :artist
  = f.input :title
  = f.input :instrument
  = f.button :submit

= simple_form_for @wishlist, method: :delete do |f|
  = f.button :submit, "Delete"

app/views/wishlists/new.html.slim
= simple_form_for @wishlist do |f|
  = f.input :artist
  = f.input :title
  = f.input :instrument
  = f.button :submit